GET http://localhost:5000/devices/lights

###

DELETE http://localhost:3000/data/1


###


PUT http://localhost:5000/data/1
Content-Type: application/json

{
    "id": "1",
    "name": "indoor1",
    "humedad": "70",
    "temperatura": "27",
    "cooler": "1",
    "extractor": "0",
    "iluminacion": "0",
    "riego": "1"
 }



###
POST http://localhost:5000/post
Content-Type: application/json

{
    "id": "3",
    "name": "indoor3",
    "humedad": "70",
    "temperatura": "27",
    "cooler": "1",
    "extractor": "0",
    "iluminacion": "0",
    "riego": "1"
 }

###

PUT http://localhost:5000/lights/data/1
Content-Type: application/json

{
    "estado": 1
 }

###
